version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - nodejs

  nodejs:
    build:
      context: ./nodejs
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./nodejs:/app
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: fullcycle
      MYSQL_USER: root
      MYSQL_PASSWORD: rootpass
    ports:
      - "3306:3306"
    volumes:
      - ./db/data:/var/lib/mysql
    restart: always
